### ISSUE TITLE
PHPUBG in Laravel

### ISSUE THREAD

**Issue by BestRicky** [MCMainiac/PHPUBG#2]
![image](https://user-images.githubusercontent.com/17917532/30767511-96e72472-a02f-11e7-81ff-f291bfd81388.png)
**I added "require *" and "use *" ,the debug shows:**
![image](https://user-images.githubusercontent.com/17917532/30767544-fc27b9d2-a02f-11e7-871e-ea8b63bcf861.png)

**Comment by kiwinam** [comment]
I was experience like you and solved changing permission.

**Comment by BestRicky** [comment]
@mals93 change file permission ? I give the file folder "./vendor " chmod 777 but not work 
can you tell me more details?  thank you

**Comment by BestRicky** [comment]
I solved my  Laravel problem.
I will show details on here:
1.open ../composer.json
2.
` "autoload": {
        "classmap": [
            "database",
            "vendor/mcmainiac/phpubg"
        ],
        "psr-4": {
            "App\\": "app/",
            "Tests\\": "tests/"
        }
    },`
done
